### ISSUE TITLE
UpdateConditionNotSatisfied when persisting Saga state

### ISSUE THREAD

**Issue by ottarhenanger** [Particular/NServiceBus.Persistence.AzureStorage#114]
Hi,

messages are rolled back due to exception when Saga is trying to persist the saga data. 

Stack-trace below illustrates the problem.

```
 <package id="NServiceBus" version="6.0.0" targetFramework="net461" />
  <package id="NServiceBus.Autofac" version="6.0.0" targetFramework="net461" />
  <package id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="7.0.2" targetFramework="net461" />
  <package id="NServiceBus.Azure.Transports.WindowsAzureStorageQueues" version="7.0.0" targetFramework="net461" />
  <package id="NServiceBus.Persistence.AzureStorage" version="1.0.0" targetFramework="net461" />
 <package id="WindowsAzure.Storage" version="7.2.1" targetFramework="net461" />
```

```
2016-11-11 13:31:08.003 INFO  NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier Exceptions occurred OnComplete
Microsoft.WindowsAzure.Storage.StorageException: Element 0 in the batch returned an unexpected response code.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Persistence.AzureStorage.AzureSagaPersister.<Persist>d__10.MoveNext() in C:\Build\src\NServiceBus.Persistence.AzureStorage\SagaPersisters\AzureSagaPersister.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.SagaPersistenceBehavior.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Sagas\SagaPersistenceBehavior.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Plugin.SagaAudit.CaptureSagaStateBehavior.<Invoke>d__5.MoveNext() in C:\BuildAgent\work\83542c77b87f97e8\src\ServiceControl.Plugin.Nsb6.SagaAudit\CaptureSagaStateBehavior.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\Incoming\LoadHandlersConnector.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.InvokeSagaNotFoundBehavior.<Invoke>d__0.MoveNext() in C:\Build\src\NServiceBus.Core\Sagas\InvokeSagaNotFoundBehavior.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MutateIncomingMessageBehavior.<Invoke>d__0.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\MutateInstanceMessage\MutateIncomingMessageBehavior.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\Incoming\DeserializeLogicalMessagesConnector.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.InvokeAuditPipelineBehavior.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Audit\InvokeAuditPipelineBehavior.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MutateIncomingTransportMessageBehavior.<Invoke>d__0.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\MutateTransportMessage\MutateIncomingTransportMessageBehavior.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.UnitOfWorkBehavior.<Invoke>d__0.MoveNext() in C:\Build\src\NServiceBus.Core\UnitOfWork\UnitOfWorkBehavior.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at NServiceBus.UnitOfWorkBehavior.<Invoke>d__0.MoveNext() in C:\Build\src\NServiceBus.Core\UnitOfWork\UnitOfWorkBehavior.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext() in C:\Build\src\NServiceBus.Core\Performance\Statistics\ProcessingStatisticsBehavior.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ReceivePerformanceDiagnosticsBehavior.<Invoke>d__2.MoveNext() in C:\Build\src\NServiceBus.Core\Performance\Statistics\ReceivePerformanceDiagnosticsBehavior.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AzureServiceBus.TransactionScopeSuppressBehavior.<Invoke>d__0.MoveNext() in C:\Build\src\Transport\Receiving\TransactionScopeSuppressBehavior.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\MainPipelineExecutor.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<<Init>b__10_1>d.MoveNext() in C:\Build\src\Transport\Seam\MessagePump.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<ProcessMessageAsync>d__32.MoveNext() in C:\Build\src\Transport\Receiving\MessageReceiverNotifier.cs:line 210
Request Information
RequestID:6472e8e0-0002-009d-4417-3c6792000000
RequestDate:Fri, 11 Nov 2016 12:31:07 GMT
StatusMessage:The update condition specified in the request was not satisfied.
ErrorCode:UpdateConditionNotSatisfied
```

**Comment by ramonsmits** [comment]
@ottarhenanger Azure Storage doesn't support locking/transactions. It only supports atomic operations. Updates done via [optimistic concurrency control](https://en.wikipedia.org/wiki/Optimistic_concurrency_control). When the same data is being read concurrently and then updated only 1 will win, the other will fail because the optimistic concurrency check will fail.

That is the behavior that you are experiencing.

If this happens a lot that means that you have a lot of congestion on the same data (row/document). It might be better to reduce the maximum amount of concurrency or even switch over to sequential processing. An alternative would be to redesign your data access strategy to remove congestion if that is possible.

If this doesn't happen continuously, then it is safe to ignore these. NServiceBus performs immediate and delayed retries to recover from such issues.

**Comment by Scooletz** [comment]
Ping @ramonsmits Can we close this?

**Comment by ottarhenanger** [comment]
This can be closed. Problem solved by ensuring that each message processed by Saga had a unique message id. Problem was caused by multiple messages having same message id used to look up saga state.

**Comment by Scooletz** [comment]
Thx for this info @ottarhenanger I'm closing it.

**Comment by ramonsmits** [comment]
@ottarhenanger Can you share details on how your message got duplicate message ID's? I currently don't see a link between that and the optimistic concurrency control as having unique message id's would result in the same behavior is both access the same saga instance.

**Comment by ottarhenanger** [comment]
My message processed by a Saga used an message identifier (MessageId) which was reused across multiple, different messages. The messages was processed in parallel by multiple cluster nodes. 

The result was that the saga was updated and completed on one cluster node, while another node was processing another message with the same id. This seem to cause the conflict.

**Comment by ramonsmits** [comment]
@ottarhenanger How to you currently prevent that now not multiple messages are being send?

**Comment by ottarhenanger** [comment]
There was a bug in my code that re-used identifiers across messages. Now each message will be assigned a unique Guid.

**Comment by ramonsmits** [comment]
@ottarhenanger I understand that now your message have unique ID's, but I fail to see how that can resolve this issue.  Maybe we are not aligned. When I say message ID I mean [message identify](https://docs.particular.net/nservicebus/messaging/message-identity), maybe you are referring to a message property used for mapping your saga instances?

**Comment by ottarhenanger** [comment]
Yes, I'm referring to message property used for mapping saga instances.

The problem in this issue can be recreated as follow:

- Create multiple instances of the same bus message, but use the same message property value for the property used to mapping to Saga instances
- Make sure the messages are consumed in parallel, for instance by different servers in a cluster

The problem seem to occur when Saga instances starts calling MarkAsComplete.

So I solved our problem but simply ensuring that each bus message did not reuse values for the property used as Saga instance mapping.

**Comment by ramonsmits** [comment]
@ottarhenanger Thanks for that. That is about saga identifiers/instances and now I understand how that resolves your issue. What you did was removing congestion on a single saga instance which is indeed a good solution to prevent OCC related errors.
