### ISSUE TITLE
NullReferenceException when transport incompatible subscriptions are retrieved

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Persistence.AzureStorage#153]
The subscription storage not compatible with subscriptions from the previous package. It seems subscriptions are not migrated or that backward compatibility is added for previous subscription items.

## How to reproduce

- Take a core 5 subscriber and publisher
- Run both and let the publisher publish a message
- Keep subscriber running (or disable auto-subscribe feature)
- Upgrade publisher to core 6 including updating azure persistence
- Run publisher and let it publish an event for the existing subscriber (this fails!)

## Data corruption/loss

In my scenarios this resulted in message loss due to the fact that a saga published a message and then completed. The publish failed, the message got retried, but because the saga was already deleted the saga now did not exist and the publish will never happen.

## Exception

```
2017-07-21 16:20:20.948 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message 'a1a1fd29-1155-4c39-857e-a7b700ec45a0' because of an exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.AzureStorageQueues.Dispatcher.<Send>d__2.MoveNext() in C:\BuildAgent\work\4e5353dd260f0a07\src\Transport\Dispatcher.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\MainPipelineExecutor.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AzureStorageQueues.AtLeastOnceReceiveStrategy.<Receive>d__1.MoveNext() in C:\BuildAgent\work\4e5353dd260f0a07\src\Transport\AtLeastOnceReceiveStrategy.cs:line 27
```

I

**Comment by Scooletz** [comment]
Do you have a repro for this? (initial v5 version? )

**Comment by Scooletz** [comment]
@ramonsmits Can you update the title and the description of the issue accordingly to your recent finding?

**Comment by ramonsmits** [comment]
@Scooletz better?

**Comment by SeanFeldman** [comment]
@ramonsmits so I'd it still qualified as as Data corruption/loss scenario?

**Comment by ramonsmits** [comment]
@SeanFeldman As far as I can see is that if the transport operation fails of pushing a message to the transport happens after deleting the saga instance so yes, the corruption/loss would still occur.

**Comment by ramonsmits** [comment]
Question is, can this even be avoided when using a non-transactional transport and an atomic storage? The whole saga probably needs to be idempotent and buffered sends be disabled.

**Comment by SeanFeldman** [comment]
@ramonsmits this has been addressed in the doco. You cannot dispatch messages and complete a saga in the same handler. You need to do one at a time. I.e. we guide in doco to dispatch an additional message to saga itself to complete. That way if sends are failing, saga won't be completed.

Closing this. If you still think it's not addressing the issue, please schedule a call so that we can handle it efficiently. Thanks :smiley:
